version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  browser-tools: circleci/browser-tools@1.1.3
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-browsers
    working_directory: ~/Smart_With_App/src
    steps:
      - checkout:
          path: ~/Smart_With_App
      - ruby/install-deps

  rspec:
    docker:
      - image: cimg/ruby:2.7-browsers
    working_directory: ~/Smart_With_App/src
    steps:
      - checkout
      - ruby/install-deps
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: bin/rails db:schema:load --trace
      - ruby/rspec-test

  rubocop:
    docker:
      - image: cimg/ruby:2.7-browsers
    working_directory: ~/Smart_With_App/src
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  deploy:
    docker:
      - image: cimg/ruby:2.7-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - rspec:
          requires:
          - build
      - rubocop:
          requires:
          - build
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: develop
