version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  browser-tools: circleci/browser-tools@1.1.3
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
    working_directory: ~/Smart_With_App/src
    steps:
      - checkout:
          path: ~/Smart_With_App
      - ruby/install-deps

  rspec:
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/Smart_With_App/src
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - ruby/install-deps
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: bin/rails db:schema:load --trace
      - ruby/rspec-test
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  rubocop:
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
    working_directory: ~/Smart_With_App/src
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - ruby/install-deps
      - ruby/rubocop-check
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    docker:
      - image: cimg/ruby:2.7-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - rspec:
          requires:
          - build
      - rubocop:
          requires:
          - build
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: develop
